artifact_uri: file:c:/Users/TARANG KISHOR/Desktop/PROJECTS/PXY/runs/mlflow/883963607226592498/6166978c84c546c5b86f7b27dd304cd2/artifacts
end_time: null
entry_point_name: ''
experiment_id: '883963607226592498'
lifecycle_stage: active
run_id: 6166978c84c546c5b86f7b27dd304cd2
run_name: bird_drone_detection
source_name: ''
source_type: 4
source_version: ''
start_time: 1763214944436
status: 1
tags: []
user_id: TARANG KISHOR
