artifact_uri: file:c:/Users/TARANG KISHOR/Desktop/PROJECTS/PXY/runs/mlflow/883963607226592498/0afd33d90e29486cb2cddf39adc6a682/artifacts
end_time: null
entry_point_name: ''
experiment_id: '883963607226592498'
lifecycle_stage: active
run_id: 0afd33d90e29486cb2cddf39adc6a682
run_name: bird_drone_detection2
source_name: ''
source_type: 4
source_version: ''
start_time: 1763278782707
status: 1
tags: []
user_id: TARANG KISHOR
