artifact_location: file:c:/Users/TARANG KISHOR/Desktop/PROJECTS/PXY/runs/mlflow/0
creation_time: 1763214941095
experiment_id: '0'
last_update_time: 1763214941095
lifecycle_stage: active
name: Default
